function figure_all_operations(X1, Y1, X2, Y2, X3, Y3, X4, Y4)
%CREATEFIGURE5(X1, Y1, X2, Y2, X3, Y3, X4, Y4)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data
%  X4:  vector of x data
%  Y4:  vector of y data

%  Auto-generated by MATLAB on 14-Feb-2018 14:26:18

% Create figure
figure1 = figure('Name','Figure','Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'Marker','o','Color',[0 0 1]);

% Create plot
plot(X2,Y2,'Color',[1 0 0]);

% Create plot
plot(X3,Y3,'Color',[1 0 1]);

% Create plot
plot(X4,Y4,'Marker','x','Color',[0 1 0]);

% Create title
title('Object with applied operations','FontSize',13);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-10 10]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-7 7]);
box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'DataAspectRatio',[1 1 1],'PlotBoxAspectRatio',[10 7 1]);
% Create textarrow
annotation(figure1,'textarrow',[0.401094438802595 0.456602551526762],...
    [0.545339071158845 0.599892109263891],'TextColor',[1 0 0],...
    'String',{'Rotation'});

% Create textarrow
annotation(figure1,'textarrow',[0.455166524338173 0.502134927412468],...
    [0.378990731204943 0.416065911431514],'TextColor',[1 0 1],...
    'String',{'Reflection'});

% Create textarrow
annotation(figure1,'textarrow',[0.673141891891892 0.61922271331964],...
    [0.811904761904762 0.753530969545388],...
    'TextColor',[0 0.447058826684952 0.74117648601532],...
    'String',{'Original'});

% Create textarrow
annotation(figure1,'textarrow',[0.709966216216215 0.673257726129203],...
    [0.550000000000001 0.588053553038106],'TextColor',[0 1 0],...
    'String',{'Projection'});

